### ISSUE TITLE
Feature Request: Archive links as `.warc` (Web ARCive)

### ISSUE THREAD

**Issue by WeekendWarrior1** [Daniel31x13/link-warden#1]
`.warc` is a format specifically designed by the internet archive team for archiving/backing up pages:
https://archive-it.org/blog/post/the-stack-warc-file/
Would make sense to use an ISO standard format to truly help fight linkrot.

**Comment by Daniel31x13** [comment]
Good idea 👍 
I will add this to the planned features.

**Comment by rien333** [comment]
We, a Dutch archival service, might be interested in using linkwarden. Is the .warc saving feature actually completed, or still in the pipeline? 

For many actual archival services, this is quite essential and more or less mandated by law!
