### ISSUE TITLE
Publish images to docker hub

### ISSUE THREAD

**Issue by gardner** [Daniel31x13/link-warden#11]
The docker images can be automatically built and pushed to Docker Hub. This will allow users to easily incorporate the image in their docker setups.

To enable this, complete the following steps:

Sign up for a Docker Hub account: https://hub.docker.com/

- After logging in, click on your username in the top right
- Select "Account Settings" from the dropdown
- Select "Security" from the menu on the right
- Click the "New Access Token" button
- Give the token a name (e.g. github-linkwarden)
- Make sure to copy the token and save it some place secret.

Set GitHub Action Secrets:

- Visit your repo https://github.com/Daniel31x13/link-warden
- Click on "Settings" with the gear icon
- Dropdown "Secrets" under the "Security" section
- Select "Actions"
- Click "New repository secret" 
- - For "Name" use `DOCKER_HUB_USERNAME`
- - For "Value" use [your docker hub username]
- Add another secret 
- - For "Name" use `DOCKER_HUB_PASSWORD`
- - For "Value" use [the token you generated on docker hub]

Go to https://github.com/Daniel31x13/link-warden/actions to inspect the actions.

**Comment by Daniel31x13** [comment]
Can you please check your email, I had a few questions.
Thanks.

**Comment by maxime1992** [comment]
Hey guys :) Is it published now? This is closed and completed but I wasn't able to find anything for linkwarden on docker hub :thinking: I'd love to set that up on my server and it'd be a lot easier than doing it from source. An official image would be awesome! Thanks
