### ISSUE TITLE
Docker-compose: failed to deploy a stack: unable to prepare context: path "./api" not found

### ISSUE THREAD

**Issue by axsddlr** [Daniel31x13/link-warden#12]
# Issue
failed to deploy a stack: unable to prepare context: path "./api" not found

## Method
deploy via stack in portainer (2.14)

**Comment by geekedtv** [comment]
I agree. Can this be made into a self sustained stack rather than a build process? This way we can just run the stack and not have to worry about cloning in the files.

**Comment by axsddlr** [comment]
> Hello Andre, According to [here](https://github.com/portainer/portainer/issues/6390) looks like Portainer does not support relative path's, if you change all the relative path's in the docker-compose.yml to absolute path it'll be fixed. (e.g. change `./api` to `/home/USERNAME/Desktop/Projects/GitHub/link-warden/api` in `docker-compose.yml`)


still does not work, same error

**Comment by Daniel31x13** [comment]
Have you changed the whole docker-compose file with the above file? And have you change the USERNAME?

**Comment by Daniel31x13** [comment]
Also I’m gonna work on making it more convenient.

**Comment by axsddlr** [comment]
`
## This compose file can be used for development

services:
  mongo:
    image: mongo
    volumes:
      - /home/prox/docker_configs/linkwarden/mongo:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  link-warden-api:
    build: /home/prox/docker_configs/linkwarden/api
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    volumes:
      - /home/prox/docker_configs/linkwarden/api:/home/node
    ports:
      - 5002:5000
    restart: unless-stopped
    depends_on:
      - mongo

  link-warden:
    build: .
    environment:
      # - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - REACT_APP_API_HOST=http://localhost:5000
    command: npm run go
    volumes:
      - /home/node/node_modules
      - /home/prox/docker_configs/linkwarden:/home/node
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - link-warden-api`


doesnt work

**Comment by Daniel31x13** [comment]
I opened an [issue](https://github.com/portainer/portainer/issues/7181).
For now you can manually start the app via [docker compose](https://github.com/Daniel31x13/link-warden#using-docker-compose-recommended) and then manage it via Portainer Stacks.

I'll reopen this issue until further notice.

**Comment by axsddlr** [comment]
unfortunately same issue with docker-compose manually, ill try this again when its less of a hassle to setup
