### ISSUE TITLE
Container link-warden-api error: permission denied, mkdir './media/screenshots'

### ISSUE THREAD

**Issue by nskartem** [Daniel31x13/link-warden#14]
### Issue

Hello!

I'm trying to run link-warden on arm64 Ubuntu in Docker. I've installed docker-compose v2, as mentioned in issues, but I'm getting another strange error - container `link-warden-api` are restarting in the loop with error `Error: EACCES: permission denied, mkdir './media/screenshots'`. I've thought, that problem was in the edits I made in `docker-compose.yml`, but error still persists, when I'm trying to run original `docker-compose.yml` from repository.
I've tried to make dir `/media/screenshots` in the root of the repository, and in the `/api` subdir, but error still presents.
Could you please help me? If you need an additional information, I could try to find something else.

### Prerequisites:

OS:
```
# cat /etc/issue
Ubuntu 20.04.3 LTS \n \l
```
Arch: arm64
Docker/docker compose version:
```
# docker compose version
Docker Compose version v2.9.0
```
```
# docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:05 2021
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true
```

### Steps to reproduce:

1. Clone repository;
2. Run `docker compose up -d` inside repository directory.

### Result:

Container `link-warden-api` are restarting in the loop with error below:
```
node:internal/fs/utils:348
    throw err;
    ^

Error: EACCES: permission denied, mkdir './media/screenshots'
    at Object.mkdirSync (node:fs:1394:3)
    at Object.<anonymous> (/home/node/server.js:24:6)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: './media/screenshots'
}

Node.js v18.7.0
```

**Comment by Daniel31x13** [comment]
Hello there!
Have you run the app with `sudo`?
Looks like it needs a higher privilege.

**Comment by nskartem** [comment]
Hello!

Docker is running as a systemd service, and I'm running all the commands as a superuser.
Could you please tell me, where are api trying to create that directory in the container? Maybe there is some problem with Docker volumes.

**Comment by nskartem** [comment]
@Daniel31x13, I finally found out what's wrong - I've set permissions on /api to 777, and dir was created successfully.

Thank you!
