### ISSUE TITLE
link-warden-api_1  | Error: Cannot find module 'express'

### ISSUE THREAD

**Issue by nedx86** [Daniel31x13/link-warden#15]
git clone
docker-compose up --build

or

git clone
npm update --force
npm run build
docker-compose up --build

--

.env file uses wrong ip

**Comment by Daniel31x13** [comment]
Hello @nedx86,
Does it work without the `—build` flag?

Can you provide me how you managed the .env file?

**Comment by nskartem** [comment]
https://github.com/Daniel31x13/link-warden/issues/13
