### ISSUE TITLE
Mixed content when running link-warden with reverse proxy and https 

### ISSUE THREAD

**Issue by nskartem** [Daniel31x13/link-warden#16]
### Issue

Hello again!

Now I'm getting mixed content error in browser, when frontend trying to talk to backend.

### Prerequisites:

link-warden in docker behind reverse proxy, serving https.

### Steps to reproduce:

1. Run link-warden behind reverse proxy (traefik, in my case);
2. Try to add bookmark with "+" button.

### Result:

I'm getting error in browser console:
```
send.js:30 Mixed Content: The page at 'https://domain.com' was loaded over HTTPS, but requested an insecure resource 'http://link-warden-api:5500/api'. This request has been blocked; the content must be served over HTTPS.
addItem @ send.js:30
```
```
send.js:30          Uncaught (in promise) TypeError: Failed to fetch
    at addItem (send.js:30:1)
    at newItem (AddItem.js:24:1)
    at AwesomeButton.action (index.js:1:1)
    at AwesomeButton.pressOut (index.js:1:1)
    at onMouseUp (index.js:1:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4157:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4206:1)
    at invokeGuardedCallback (react-dom.development.js:4270:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4284:1)
    at executeDispatch (react-dom.development.js:9011:1)
```

Also I've got websocket error:
```
WebSocketClient.js:16 WebSocket connection to 'wss://domain.com:3000/ws' failed: 
```
But that's probably because I exposed port 3000 only to reverse proxy, I don't have a possibility to open that port to internet on that VM.

**Comment by Daniel31x13** [comment]
Hello there!
LinkWarden needs 2 open ports (3000 for the front-end and 5000 for the back-end as default).

To change the default ports, please take a look at  [Configuration](https://github.com/Daniel31x13/link-warden#configuration).

**Comment by Daniel31x13** [comment]
@nskartem Is the problem fixed?

**Comment by AlienPie** [comment]
In case it helps, you can create a Reverse Proxy entry for the API Enpoint for HTTPS forwarding to port 5500. In the *.env* file, add:

```
API_PORT=443
API_ADDRESS=lw-api.domain.net
```

This should allow the front-end to call the API over HTTPS, just be careful with your domain name resolution and firewalling if you're accessing internally and externally.
