### ISSUE TITLE
API problem - restarting status

### ISSUE THREAD

**Issue by tarzinio** [Daniel31x13/link-warden#18]
Hi,

I have a problem with the application, namely the API. I still have restarting status. What could be wrong?

![image](https://user-images.githubusercontent.com/29274594/187682737-6b894a2f-d123-4ed5-9375-35544d29ae97.png)
![image](https://user-images.githubusercontent.com/29274594/187682813-cdc06acf-4ad5-4b3a-9187-efb16434cc14.png)

I tried to restart with the command "`docker docker compose restart`" but it doesn't help.

Can someone help me?

**Comment by AlienPie** [comment]
Always start by checking the logs:
`docker logs -f link-warden-link-warden-api-1`
Ctrl + C to leave that screen.
Logs should show you what is happening before the container restarts and give you an idea of where the problem will lie. If a container is restarting it usually means it's failing a defined healthcheck in the dockerfile/compose file.
Noticing that your API container isn't mapping any exposed ports. You may want to look into that as well.
