### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by benharvie** [Daniel31x13/link-warden#19]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@tasosy2k) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by Daniel31x13** [comment]
Hello there!

Thank you for putting the time on this project and really sorry for the late response, was really busy these days…

I’ve created the `SECURITY.md` and here’s my email: daniel31x13@gmail.com

Thanks again!

**Comment by Daniel31x13** [comment]
I’m rebuilding this project, again, thank you for putting your time and sorry for being unresponsive.

I’m busy with my job and its a bit hard to get to multiple things at once…

**Comment by psmoros** [comment]
> I’m rebuilding this project, again, thank you for putting your time and sorry for being unresponsive.
> 
> I’m busy with my job and its a bit hard to get to multiple things at once…

Don't mention it! Thank *you* for your project and responsive maintenance <33

I work with Ben btw :)
