### ISSUE TITLE
Clickable tags, title and more suggestions

### ISSUE THREAD

**Issue by geekedtv** [Daniel31x13/link-warden#2]
First, this looks really great! I just have a couple suggestions.

Clickable tags so we can see each link in that tag like categories.

Clickable title to go to the link.

Lists where we can further define groups of links.

Public links are great but only allow admins to add links.

**Comment by Daniel31x13** [comment]
Clickable tags: This is exactly what I want to add in the sidebar in the planned features alongside folders to group link.
Clickable title: The links are already clickable.

**Comment by ItsNoted** [comment]
Can we delete or edit tags we create? If so I don't see how.

**Comment by AuthorShin** [comment]
After clicking on a tag from left menu, in the new page there's a three-dot icon next to the tag's name to rename and delete it.
