### ISSUE TITLE
[Feature Request] Mobile PWA

### ISSUE THREAD

**Issue by BadCo-NZ** [Daniel31x13/link-warden#20]
Hi there,

I'm looking at starting to use a bookmark manager, and Link Warden looks like a great option.

While the mobile experience is good in the demo, is there a possibility of making it a PWA?

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps

Thanks

**Comment by Daniel31x13** [comment]
Hello there,

I will keep this feature request in mind…

Thanks for the idea!
