### ISSUE TITLE
Add Docker support

### ISSUE THREAD

**Issue by joshdavidson** [Daniel31x13/link-warden#3]
Add Dockerfile to project and update README.md with instructions on how to build/run the docker image.  Also add in github action for autobuilding image on commit...

**Comment by Daniel31x13** [comment]
I’ve already added docker support to the [project roadmap](https://github.com/Daniel31x13/link-warden/wiki).

**Comment by Daniel31x13** [comment]
I’ve noticed you forked this repo, if you want to contribute by adding docker support then yes I do need help with it.

Thank you.

**Comment by joshdavidson** [comment]
Awesome - I’d be happy to help!
